# Generated by Django 3.2.4 on 2021-06-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_auto_20210614_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='particiant',
            new_name='particiants',
        ),
    ]
