# Generated by Django 3.2.4 on 2021-06-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_rename_particiant_meetup_particiants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Particiant',
            new_name='Participant',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='particiants',
        ),
        migrations.AddField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='meetups.Participant'),
        ),
    ]
